name: DockerHub Image Deployment

on:
  push: # every commit
    branches:
      - 'master'
  schedule: # every quarter
    - cron:  '0 0 1 1,4,7,9 *'

jobs:
  build:
    name: Prepare, build and deploy
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set image tag
        run: echo "IMAGE_TAG=$(date +%Y.%m.%s)" >> $GITHUB_ENV
   
      - name: Print variable tag
        run: echo "Tag is $IMAGE_TAG"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/amd64,linux/arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
  
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image to DockerHub
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm64
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/alps:${{ env.IMAGE_TAG }}, ${{ secrets.DOCKERHUB_USERNAME }}/alps:latest
          push: true
